kind: ConfigMap
metadata:
  namespace: ${kubernetes.namespace}
  name: ${git.branch}-config-map
  labels:
    branch: ${git.branch}
spec:
  selector:
    branch: ${git.branch}
data:
  active-profiles: DEV
  time-zone: Europe/Zurich